### ISSUE TITLE
控制台进程为什么不会自动关掉或隐藏？

### ISSUE THREAD

**Issue by FTS427** [Blessing-Studio/WonderLab.Override#1]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题
- [X] 查看 [Actions](https://github.com/Blessing-Studio/WonderLab/Actions) 中最新Dev版是否已修复你所遇到的问题

### 问题描述

![image](https://github.com/Blessing-Studio/WonderLab.Override/assets/122330825/084ae038-37aa-4c66-afec-785963719305)
图中的这个控制台进程为什么不可以关掉？
或者隐藏？

### 日志

无

### 问题复现率

必现

### 复现步骤

1. 拉取最新版本（1.2.5）
2. 解压并运行

### 操作系统版本

Windows

### WonderLab版本

1.2.5

### 补充信息

这个新版本的UI和之前的好不一样啊！（赞叹）
还有就是之前的那个版本怎么被存档了？

**Comment by YangSpring114** [comment]
这是打包方法用的不一样的原因，如果可以的话，建议在群里下最新的，那是我手动编译的，不会出现这种问题
