### ISSUE TITLE
QQ-ic58nN Java不手动选择时将不被自动选择

### ISSUE THREAD

**Issue by JWJUN233233** [Blessing-Studio/WonderLab.Override#10]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab.Override/issues) 列表中是否有相似问题
- [X] 查看 [CI](https://github.com/Blessing-Studio/WonderLab.Override/release) 中最新自动构建版是否已修复你所遇到的问题

### 问题描述

如标题

### 问题复现率

必现

### 复现步骤

如标题

### 操作系统版本

全平台

### WonderLab版本

1.2.5-preview

**Comment by YangSpring114** [comment]
修好了
