### ISSUE TITLE
霍，这里出现了错误

### ISSUE THREAD

**Issue by Starcloudsea** [Blessing-Studio/WonderLab.Override#18]
### ❗ 检查表

- [x] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab.Override/issues) 列表中是否有相似问题
- [x] 查看 [CI](https://github.com/Blessing-Studio/WonderLab.Override/release) 中最新自动构建版是否已修复你所遇到的问题

### 问题描述

![Image](https://github.com/Blessing-Studio/WonderLab.Override/assets/84891987/230e2479-f826-498e-a6ae-616cd5187ce5)

### 日志

看图片

### 问题复现率

必现

### 复现步骤

刷新服务器匣子时会复现

### 操作系统版本

全平台

### WonderLab版本

1.2.6

### 插件信息

None

**Comment by FTS427** [comment]
这个我好像也遇到过，当时好像说的是网络连接不好导致的

**Comment by JWJUN233233** [comment]
服务器的问题
