### ISSUE TITLE
建议把linux版的安装包统一为Appimage可执行文件

### ISSUE THREAD

**Issue by FTS427** [Blessing-Studio/WonderLab.Override#19]
### 建议描述

把linux版的安装包同一为Appimage文件，避免release下一堆linux版
Appimage类似于Windows上的携带版程序，有助于linux上的软件统一
这个是他的一些说明和如何打包：https://doc.appimage.cn/docs/appimage/
（这样也可以避免Archlinux上的AUR因为本地编译时间太长的问题）

### 操作系统版本

Linux

### WonderLab版本

1.2.6-preview

### 补充信息

Appimage真的很好用，跨linux发行版，双击即可打开（需要附权限）
并且打包也不难，GitAction应该可以做到

**Comment by JWJUN233233** [comment]
这个用actions的实现难度有点大 可能会推迟一周 等我研究

**Comment by FTS427** [comment]
> 这个用actions的实现难度有点大 可能会推迟一周 等我研究

行，不急

**Comment by FTS427** [comment]
> 这个用actions的实现难度有点大 可能会推迟一周 等我研究

这个官方给的有GitAction的示范[链接仓库](https://github.com/AppImageCrafters/build-appimage)

可以参考

**Comment by mailset** [comment]
已解决
