### ISSUE TITLE
上传至Archlinux的AUR仓库

### ISSUE THREAD

**Issue by FTS427** [Blessing-Studio/WonderLab.Override#2]
### 建议描述

建议上传至AUR

### 操作系统版本

Linux

### WonderLab版本

1.2.5

**Comment by FTS427** [comment]
> 我是wonderlab-git目前的维护者，我倒是想更新，但是在我的设备上自行编译和下载Release都无法运行，所以我也没辙（

是可以正常运行的
1、下载"wonderlab.1.2.6-preview.linux-x64.zip"
2、解压
3、创建一个shell脚本（在wonderlab根目录下），写入以下：
`#! sh
export LC_CTYPE=en_US.UTF-8 && ./wonderlab`
4、运行时启动shell脚本即可（desktop的话，需要改，二进制文件指向shell脚本即可）

**Comment by MCSeekeri** [comment]
wonderlab-git已经更新，理论上应该可用了。
`另外我很想吐槽为什么生成的二进制里面带了这么多dll……真的全都是必要的吗……`
`而且目前糟心的版本号管理导致我只能写成拉取当前最新的代码……`

**Comment by MCSeekeri** [comment]
> > wonderlab-git已经更新，理论上应该可用了。
> > `另外我很想吐槽为什么生成的二进制里面带了这么多dll……真的全都是必要的吗……`
> > `而且目前糟心的版本号管理导致我只能写成拉取当前最新的代码……`
> 
> 行，版本号可以暂时写AutoBuild_master

我不认为这是个好主意（

**Comment by FTS427** [comment]
> > > wonderlab-git已经更新，理论上应该可用了。
> > > `另外我很想吐槽为什么生成的二进制里面带了这么多dll……真的全都是必要的吗……`
> > > `而且目前糟心的版本号管理导致我只能写成拉取当前最新的代码……`
> > 
> > 行，版本号可以暂时写AutoBuild_master
> 
> 我不认为这是个好主意（

雀食

**Comment by FTS427** [comment]
反正可以直接从AUR里直接下载了，就很棒了

**Comment by JWJUN233233** [comment]
> wonderlab-git已经更新，理论上应该可用了。
> 
> `另外我很想吐槽为什么生成的二进制里面带了这么多dll……真的全都是必要的吗……`
> 
> `而且目前糟心的版本号管理导致我只能写成拉取当前最新的代码……`

真的必要 这些dll都是dotnet程序 跨平台

**Comment by MCSeekeri** [comment]
> > wonderlab-git已经更新，理论上应该可用了。
> > `另外我很想吐槽为什么生成的二进制里面带了这么多dll……真的全都是必要的吗……`
> > `而且目前糟心的版本号管理导致我只能写成拉取当前最新的代码……`
> 
> 真的必要 这些dll都是dotnet程序 跨平台

源码编译，只在Linux x64上面跑，这种情况下生成的二进制为啥还需要考虑跨平台……

**Comment by JWJUN233233** [comment]
> > > wonderlab-git已经更新，理论上应该可用了。
> 
> > > `另外我很想吐槽为什么生成的二进制里面带了这么多dll……真的全都是必要的吗……`
> 
> > > `而且目前糟心的版本号管理导致我只能写成拉取当前最新的代码……`
> 
> > 
> 
> > 真的必要 这些dll都是dotnet程序 跨平台
> 
> 
> 
> 源码编译，只在Linux x64上面跑，这种情况下生成的二进制为啥还需要考虑跨平台……

c#不会生成二进制代码 所以只能生成跨平台的
