### ISSUE TITLE
游戏安装器里所有模组、光影加载器的简介全部乱码

### ISSUE THREAD

**Issue by FTS427** [Blessing-Studio/WonderLab.Override#25]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab.Override/issues) 列表中是否有相似问题
- [X] 查看 [CI](https://github.com/Blessing-Studio/WonderLab.Override/release) 中最新自动构建版是否已修复你所遇到的问题

### 问题描述

正如标题所说：游戏安装里所有模组、光影加载器的简介全部乱码
![image](https://github.com/Blessing-Studio/WonderLab.Override/assets/122330825/125012f2-3713-4e15-9f7c-6b70382764f7)
![image](https://github.com/Blessing-Studio/WonderLab.Override/assets/122330825/ce9bd94b-9854-4ece-9dcb-df9b4d6e4e1e)

### 问题复现率

必现

### 复现步骤

打开“游戏安装”的界面就会出现这种问题

### 操作系统版本

Linux

### WonderLab版本

1.2.6-preview

### 补充信息

这个上古问题快解决啊，乱码看不明白

**Comment by JWJUN233233** [comment]
编码问题 可能得设置一下编译选项
