### ISSUE TITLE
建议在创建离线账户时胡乱写的时候检查格式

### ISSUE THREAD

**Issue by FTS427** [Blessing-Studio/WonderLab.Override#32]
### 建议描述

建议在创建离线账户时胡乱写的时候检查格式，否则出现下图的报错可能会导致用户认为是wonderlab自身问题
![image](https://github.com/Blessing-Studio/WonderLab.Override/assets/122330825/9e26090a-1652-4d34-8666-e27c92031ca2)

### 操作系统版本

Linux

### WonderLab版本

1.2.6-preview

### 补充信息

这个之前不是在群里说过吗？

**Comment by mailset** [comment]
具体的复现步骤能够说明一下吗

**Comment by FTS427** [comment]
> 具体的复现步骤能够说明一下吗

例如：
在创建离线用户时，所有信息输入”114“，就会出现这个报错
