### ISSUE TITLE
在Issues里使用“建议反馈”模板建议时，模板里的“操作系统版本”加上”全平台“

### ISSUE THREAD

**Issue by FTS427** [Blessing-Studio/WonderLab.Override#33]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab.Override/issues) 列表中是否有相似问题
- [X] 查看 [CI](https://github.com/Blessing-Studio/WonderLab.Override/release) 中最新自动构建版是否已修复你所遇到的问题

### 问题描述

在Issues里使用“建议反馈”模板建议时，模板里的“操作系统版本”加上”全平台“

### 问题复现率

必现

### 复现步骤

在[选择Issues类型](https://github.com/Blessing-Studio/WonderLab.Override/issues/new/choose)中选“建议反馈”

### 操作系统版本

全平台

### WonderLab版本

1.2.6-preview

**Comment by mailset** [comment]
看错了（

**Comment by mailset** [comment]
不是有吗

**Comment by mailset** [comment]
已解决
