### ISSUE TITLE
如果在安装整合包时为什么也可以启动没有安装好的整合包

### ISSUE THREAD

**Issue by FTS427** [Blessing-Studio/WonderLab.Override#37]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab.Override/issues) 列表中是否有相似问题
- [X] 查看 [CI](https://github.com/Blessing-Studio/WonderLab.Override/release) 中最新自动构建版是否已修复你所遇到的问题

### 问题描述

如果在安装整合包时为什么也可以启动没有安装好的整合包，并且弹出“启动成功”
不过启动之后等一会就会出现下图的报错
![image](https://github.com/Blessing-Studio/WonderLab.Override/assets/122330825/c19e3b0c-624c-41e7-b534-72a082c4c337)

### 问题复现率

必现

### 复现步骤

1.先在wonderlab导入一个正常的整合包
2.在整合包未完成安装时选择整合包版本
3.启动游戏
4.出现问题

### 操作系统版本

全平台

### WonderLab版本

1.2.6-preview

**Comment by YangSpring114** [comment]
这个是特性，因为整合包安装优先级是先下载游戏核心，然后下载整合包配套的资源文件，你看到的没安装完应该是还在下配套资源
