### ISSUE TITLE
在“核心信息”中的分辨率设置为什么什么字符都可以输入？

### ISSUE THREAD

**Issue by FTS427** [Blessing-Studio/WonderLab.Override#38]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab.Override/issues) 列表中是否有相似问题
- [X] 查看 [CI](https://github.com/Blessing-Studio/WonderLab.Override/release) 中最新自动构建版是否已修复你所遇到的问题

### 问题描述

在“核心信息”中的分辨率设置为什么什么字符都可以输入（包括特殊符号、汉字、字母）如下图：
![image](https://github.com/Blessing-Studio/WonderLab.Override/assets/122330825/55eb8a8d-0465-4b77-830e-b6c521e093ff)

建议加以限制，只允许整形数值输入

### 问题复现率

必现

### 复现步骤

1.启动wonderlab
2.点击“当前核心”
3.随便找一个核心点击信息按钮
4.设置分辨率
5.问题出现

### 操作系统版本

全平台

### WonderLab版本

1.2.6-preview

**Comment by mailset** [comment]
已解决
