### ISSUE TITLE
releases中不必再留下linux版的zip/deb/rpm的打包了

### ISSUE THREAD

**Issue by FTS427** [Blessing-Studio/WonderLab.Override#42]
### 建议描述

releases中不必再留下linux版的zip/deb/rpm的打包了，因为已经有appimage了，appimage跨linux发行版，所以不必再留下linux版的zip/deb/rpm的打包了，这样会很浪费资源

### 操作系统版本

全平台

### WonderLab版本

1.2.6-preview

**Comment by JWJUN233233** [comment]
deb和rpm还是有必要的
