### ISSUE TITLE
游戏内存设置可以设置成大于用户内存的数值

### ISSUE THREAD

**Issue by FTS427** [Blessing-Studio/WonderLab.Override#46]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab.Override/issues) 列表中是否有相似问题
- [X] 查看 [CI](https://github.com/Blessing-Studio/WonderLab.Override/release) 中最新自动构建版是否已修复你所遇到的问题

### 问题描述

游戏内存设置可以设置成大于用户内存的数值，建议添加一个比较功能如：

先获取用户的总内存（用户点击输入框时获取），
再获取用户已用内存（只用户点击输入框时获取，不要在后台重复获取），
以上两者相减
再把用户输入的内存数值与两者相减之差比较
如果小于等于，true
如果大于，false，清空已输入内容，让用户重新数值

还有，将内存设置的界面可以重新设计，如下：
![-3bce215c6f9d555b](https://github.com/Blessing-Studio/WonderLab.Override/assets/122330825/c68b5dcc-ad2f-4781-8a19-c3f327c76cd6)
（中间的“/”要加，不是注释）

### 问题复现率

必现

### 复现步骤

ui的问题

### 操作系统版本

全平台

### WonderLab版本

1.2.6-preview

### 补充信息

（这个算是个建议吧？）

**Comment by mailset** [comment]
已将内存设置转成Slider，所述问题已解决
