### ISSUE TITLE
版本下载时一搜索版本就会闪退

### ISSUE THREAD

**Issue by dogenotwolf** [Blessing-Studio/WonderLab.Override#51]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab.Override/issues) 列表中是否有相似问题
- [X] 查看 [CI](https://github.com/Blessing-Studio/WonderLab.Override/release) 中最新自动构建版是否已修复你所遇到的问题

### 问题描述

版本下载时一搜索版本就会闪退，切换正式、快照、远古可以，也可以输入，就是一点搜索就会直接闪退，并且设置过的背景闪退完就会恢复默认

### 问题复现率

必现

### 复现步骤

在下载版本时使用搜索

### 操作系统版本

Mac

### WonderLab版本

1.2.6

**Comment by FTS427** [comment]
背景的问题早在 #28里出现过（#28的4），至今仍然没有解决

**Comment by YangSpring114** [comment]
非常抱歉影响了您的使用，我们会火速修复这个问题，由于目前仍处于测试期，请谅解
