### ISSUE TITLE
Archlinux不能使用wonderlab.desktop文件

### ISSUE THREAD

**Issue by FTS427** [Blessing-Studio/WonderLab.Override#9]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab.Override/issues) 列表中是否有相似问题
- [X] 查看 [CI](https://github.com/Blessing-Studio/WonderLab.Override/release) 中最新自动构建版是否已修复你所遇到的问题

### 问题描述

Archlinux不能使用desktop文件，并且请求让git bot在下次打包时可以给可执行程序使用“chmod u+x”附加权限

### 问题复现率

必现

### 复现步骤

1.从github拉取最新版
2.解压并手动赋予可执行程序权限
3.双击打开wonderlab.desktop
4.启动失败

### 操作系统版本

Linux

### WonderLab版本

1.2.5

**Comment by JWJUN233233** [comment]
第一条能搞 第二条不可能实现

**Comment by FTS427** [comment]
> 第一条能搞 第二条不可能实现

为啥呀，git bot不可以吗？

**Comment by JWJUN233233** [comment]
> > 第一条能搞 第二条不可能实现
> 
> 
> 
> 为啥呀，git bot不可以吗？

dotnet build -t:CreateZip构建打包一体 没法在中间插入步骤

**Comment by FTS427** [comment]
> > > 第一条能搞 第二条不可能实现
> > 
> > 
> > 为啥呀，git bot不可以吗？
> 
> dotnet build -t:CreateZip构建打包一体 没法在中间插入步骤

好吧，这个问题解决了

**Comment by FTS427** [comment]
这个desktop是可以用的,只不过需要安装至系统
